In [20]:
import numpy as np
a = np.random.rand(100000, 3, 3)
print("随机生成的矩阵为：\n")
print(a)
print("\n矩阵的行列式值为：\n")
det_a = np.linalg.det(a)
print(det_a)
print("\n矩阵的逆为：\n")
inv_a = np.linalg.inv(a) 
print(inv_a)

随机生成的矩阵为：

[[[0.08874797 0.11424369 0.246252  ]
  [0.58697544 0.52418014 0.46841702]
  [0.17505817 0.46049012 0.34279929]]

 [[0.89958744 0.56662297 0.65724184]
  [0.40471256 0.23791639 0.61504943]
  [0.3590155  0.30268326 0.8407826 ]]

 [[0.48404716 0.05898442 0.19732686]
  [0.09814398 0.19757749 0.76505691]
  [0.04303986 0.91207878 0.16937957]]

 ...

 [[0.83782894 0.32143926 0.78516543]
  [0.64525522 0.67986486 0.01314197]
  [0.93589917 0.53549463 0.25751085]]

 [[0.45092559 0.37128046 0.33915032]
  [0.27673552 0.5809074  0.69617662]
  [0.42167212 0.80650454 0.60564442]]

 [[0.66547117 0.56932813 0.16596623]
  [0.40274503 0.46882822 0.19159024]
  [0.56341718 0.279542   0.62639327]]]

矩阵的行列式值为：

[ 0.02714887 -0.0308393  -0.30461798 ... -0.13696235 -0.05515153
  0.05246236]

矩阵的逆为：

[[[ -1.32649426   2.73432924  -2.78342023]
  [ -4.39114155  -0.46726375   3.79289487]
  [  6.5761248   -0.76866066  -0.75650723]]

 [[ -0.44977635   8.99730489  -6.23011869]
  [  3.87372561 -16.87448742   

In [41]:
import numpy as np
import random
a = np.random.rand(100000, 3, 3)
%timeit np.linalg.det(a)
%timeit np.linalg.inv(a) 

a, b, c, d, e, f, g, h, i = [random.uniform(-5,5) for _ in range(9)]
%timeit j = a*e*i+b*f*g+c*d*h-c*e*g-a*f*h-b*d*i
def fun():
    a1 = np.mat([[a, b], [c, d]])
    a2 = a1.I
%timeit fun()

29.5 ms ± 3.97 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
42.5 ms ± 5.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.03 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
47 µs ± 5.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
